image: Visual Studio 2017

version: '0.1.{build}'

before_build:
  - dotnet restore dotnet-packaging.sln

build_script:
  - dotnet pack dotnet-packaging.sln -c Release --version-suffix r%APPVEYOR_BUILD_NUMBER%

on_success:
  - ps: Push-AppVeyorArtifact dotnet-tarball\bin\Release\dotnet-tarball.0.1.1-r$($env:APPVEYOR_BUILD_NUMBER).nupkg
  - ps: Push-AppVeyorArtifact dotnet-zip\bin\Release\dotnet-zip.0.1.1-r$($env:APPVEYOR_BUILD_NUMBER).nupkg
  - ps: Push-AppVeyorArtifact dotnet-zip\bin\Release\dotnet-rpm.0.1.1-r$($env:APPVEYOR_BUILD_NUMBER).nupkg
  - ps: Push-AppVeyorArtifact Packaging.Targets\bin\Release\Packaging.Targets.0.1.1-r$($env:APPVEYOR_BUILD_NUMBER).nupkg
  
test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\Packaging.Targets.Tests\
  - cmd: dotnet restore
  - cmd: dotnet build
  - cmd: dotnet vstest bin\Debug\netcoreapp1.1\Packaging.Targets.Tests.dll /logger:trx;LogFileName=testresults.trx
  - ps: '& (Join-Path $env:APPVEYOR_BUILD_FOLDER "appveyor-testresults.ps1")'
  - cmd: cd ..